' (c) Crown copyright 2019 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.


class field_pointer_mod::field_pointer_type {
  +field_ptr: field_type <<pointer>>

}



